// <auto-generated>
//     This code was generated by a Blazonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace Blazonia.Components
{
    /// <summary>
    /// A check box control.
    /// </summary>
    public partial class CheckBox : Blazonia.Components.Primitives.ToggleButton
    {
        static CheckBox()
        {
            RegisterAdditionalHandlers();
        }

        public new AC.CheckBox NativeControl => (AC.CheckBox)((AvaloniaObject)this).NativeControl;

        protected override AvaloniaBindableObject CreateNativeElement() => new AC.CheckBox();


        static partial void RegisterAdditionalHandlers();
    }
}
