// <auto-generated>
//     This code was generated by a Blazonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using ACP = Avalonia.Controls.Primitives;
using Blazonia.Components;

#pragma warning disable CA2252

namespace Blazonia.Components.Primitives
{
    public partial class TabStrip<T> : SelectingItemsControl<T>
    {
        static TabStrip()
        {
            RegisterAdditionalHandlers();
        }

        public new ACP.TabStrip NativeControl => (ACP.TabStrip)((AvaloniaObject)this).NativeControl;

        protected override AvaloniaBindableObject CreateNativeElement() => new ACP.TabStrip();


        static partial void RegisterAdditionalHandlers();
    }
}
