name: .NET

on:
  push:
    branches: [ main, 'v[0-9].**' ]
  pull_request:
    branches: [ main, 'v[0-9].**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore BlazorBindings.Avalonia.sln
    - name: Build templates
      run: |
        cd templates
        dotnet build -c Release --no-restore
        cd ..
    - name: Pack nugets
      run: dotnet pack -o ./packages -c Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: packages

#  publish-to-myget:
#    runs-on: windows-2022
#    needs: [build]
#    steps:
#    - uses: actions/download-artifact@v3
#    
#    - name: Publish to Myget
#      run: dotnet nuget push */*.nupkg -k ${{ secrets.MYGET_TOKEN }} -s https://www.myget.org/F/blazorbindings/api/v2/package
